use_frameworks!
inhibit_all_warnings!

platform :ios, '9.0'

target 'HSBCycleScrollView' do
  pod 'SDWebImage', '>= 5.0.0'
end

target 'HSBCycleScrollView_Example' do
#  pod 'HSBCycleScrollView', :path => '../'
  pod 'Masonry'
  pod 'SDWebImage', '>= 5.0.0'

  target 'HSBCycleScrollView_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
